# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Push updates to repo
        run: |
          git clone git@github.com:AzureArcForKubernetes/TestGitOpsRepo.git
          cd TestGitOpsRepo
          git checkout master
          touch special_file
          git config --global user.email "testuser@example.com"
          git config --global user.name "Test User"
          git add .
          git commit -m "Attempting to add special file to protected branch"
          git push --set-upstream origin master
